# Generated by Django 5.1.2 on 2024-10-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_unique_together_contact_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
